### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by n7ihq** [jdelacroix/qcx_cat_fsk#1]
I tried to build the source code on a Raspberry Pi 3 B+ and got the following errors running make:

/usr/bin/ld: CMakeFiles/qcx_cat_ft8.dir/src/qcx_cat_fsk/audio_decoder.cc.o: in function `qcx_cat_fsk::AudioDecoder::Decode()':
audio_decoder.cc:(.text+0x4f4): undefined reference to `boost::log::v2s_mt_posix::trivial::logger::get()'
/usr/bin/ld: audio_decoder.cc:(.text+0x558): undefined reference to `boost::log::v2s_mt_posix::trivial::logger::get()'
/usr/bin/ld: audio_decoder.cc:(.text+0x780): undefined reference to `boost::log::v2s_mt_posix::trivial::logger::get()'
/usr/bin/ld: audio_decoder.cc:(.text+0x7e4): undefined reference to `boost::log::v2s_mt_posix::trivial::logger::get()'
/usr/bin/ld: audio_decoder.cc:(.text+0x930): undefined reference to `boost::log::v2s_mt_posix::trivial::logger::get()'
...

Can you help me solve this problem?

Thanks,
Jim N7IHQ

**Comment by jdelacroix** [comment]
Could you provide me with the output of `apt-cache policy libboost-log-dev`? I suspect that the Pi ships with a different version of Boost installed than what I used for development on my desktop.

**Comment by n7ihq** [comment]
Here is the output from apt-cache policy libboost-log-dev:

$ apt-cache policy libboost-log-dev
libboost-log-dev:
  Installed: 1.67.0.1+b1
  Candidate: 1.67.0.1+b1
  Version table:
 *** 1.67.0.1+b1 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
        100 /var/lib/dpkg/status

**Comment by jdelacroix** [comment]
Thanks! I was using 1.7.2, so I downgraded and made a change to the `CMakeLists.txt` that should fix this issue. Check out https://github.com/jdelacroix/qcx_cat_fsk/tree/dev/1-boost-log-linker. If it works for you, I'll merge the change into `development`.

**Comment by n7ihq** [comment]
The "1-boost-log-linker" code compiled successfully on my Raspberry Pi 3 B+. What arguments do I use to run the qcx_cat_ft8 command?

Thanks,
Jim N7IHQ

**Comment by jdelacroix** [comment]
It takes no arguments currently--everything is hard coded to default to the FT8 frequencies on the 40m band and a default serial port. I opened issue #3 and listed the four hard coded values that need to be changed if you want to a) use a different serial port, and b) use a different band for FT8. Until I expose these values as command-line options, you'll need to change them in the code and then recompile.

Thanks for testing the branch!

**Comment by n7ihq** [comment]
Jean-Pierre,

I would like to investigate modifying the QCX CAT FSK code to support Olivia digital mode at 31.25 baud. Could the Si5351 be programmed to shift frequencies at that rate?  The QCX firmware version >= 1.05 supports supports a 38400 baud rate serial interface. A Set Frequency CAT command would take 3.65 mSec. A comment on the Silicon Labs forum suggested that the Si5351 settling time for a multisynth divider frequency change is only 5 clock cycles. I would like your feedback on the feasibility of implementing Olivia mode.

Thanks,

Jim N7IHQ
